export const questionBanks = [
  {
    id: "nbl",
    shortName: "NBL",
    title: "NBL | तह-३ कनिष्ठ सहायक | 30 Sets",
    subtitle: "30 Sets",
    description:
      "Loksewa Nepal Bank Limited(NBL) Prasasan Sewa Level-3 Exam लोक सेवा नेपाल बैंक लिमिटेड, प्रशासन सेवा, प्रशासन समूह तह-३ कनिष्ठ सहायक पदको खुला प्रतियोगितात्मक परीक्षा पूर्ण रुपमा पाठ्यक्रम आधारित",
    bgColor: "bg-gradient-to-br from-red-500 to-red-600",
    glowColor: "bg-red-500",
    tags: ["NBL", "Banking Sector", "Government Job"],
    lastUpdated: "01 Jun",
    language: "NEPALI",
    purchases: 257,
    originalPrice: 180,
    price: 120,
    examDetails: {
      time: "30 mins",
      fullMarks: "40 marks",
      passMarks: "16 marks",
      validityTime: "365 days",
      negativeMarking: "-20 percent",
      numberOfQuestions: "20 question",
    },
    sets: [
      { id: "nbl-1", title: "NBL Level 3 Set 1", isCompleted: false },
      { id: "nbl-2", title: "NBL Level 3 Set 2", isCompleted: false },
      { id: "nbl-3", title: "NBL Level 3 Set 3", isCompleted: false },
      { id: "nbl-4", title: "NBL Level 3 Set 4", isCompleted: false },
      { id: "nbl-5", title: "NBL Level 3 Set 5", isCompleted: true },
      { id: "nbl-6", title: "NBL Level 3 Set 6", isCompleted: true },
    ],
  },
  {
    id: "civil-sub-engineer",
    shortName: "Civil Sub",
    title: "Civil Sub-Engineer | 50 Sets | सेट Syllabus",
    subtitle: "50 Sets",
    description:
      "Complete syllabus for Civil Sub-Engineer examination with 50 practice sets covering all important topics.",
    bgColor: "bg-gradient-to-br from-teal-500 to-teal-600",
    glowColor: "bg-teal-500",
    tags: ["Engineering", "Civil", "Government Job"],
    lastUpdated: "15 May",
    language: "ENGLISH",
    purchases: 189,
    originalPrice: 250,
    price: 200,
    examDetails: {
      time: "45 mins",
      fullMarks: "50 marks",
      passMarks: "20 marks",
      validityTime: "365 days",
      negativeMarking: "-25 percent",
      numberOfQuestions: "25 question",
    },
    sets: [
      { id: "civil-1", title: "Civil Sub-Engineer Set 1", isCompleted: false },
      { id: "civil-2", title: "Civil Sub-Engineer Set 2", isCompleted: false },
      { id: "civil-3", title: "Civil Sub-Engineer Set 3", isCompleted: false },
      { id: "civil-4", title: "Civil Sub-Engineer Set 4", isCompleted: false },
      { id: "civil-5", title: "Civil Sub-Engineer Set 5", isCompleted: false },
      { id: "civil-6", title: "Civil Sub-Engineer Set 6", isCompleted: false },
    ],
  },
  {
    id: "private-bank",
    shortName: "Private Bank",
    title: "Private Bank | TA and MT | 30 Sets",
    subtitle: "30 Sets",
    description:
      "Comprehensive question bank for Private Bank TA (Trainee Assistant) and MT (Management Trainee) positions.",
    bgColor: "bg-gradient-to-br from-amber-600 to-amber-700",
    glowColor: "bg-amber-600",
    tags: ["Banking", "Private Sector"],
    lastUpdated: "10 May",
    language: "ENGLISH",
    purchases: 312,
    originalPrice: 200,
    price: 150,
    examDetails: {
      time: "35 mins",
      fullMarks: "45 marks",
      passMarks: "18 marks",
      validityTime: "365 days",
      negativeMarking: "-15 percent",
      numberOfQuestions: "22 question",
    },
    sets: [
      { id: "pb-1", title: "Private Bank Set 1", isCompleted: false },
      { id: "pb-2", title: "Private Bank Set 2", isCompleted: false },
      { id: "pb-3", title: "Private Bank Set 3", isCompleted: false },
      { id: "pb-4", title: "Private Bank Set 4", isCompleted: false },
      { id: "pb-5", title: "Private Bank Set 5", isCompleted: false },
      { id: "pb-6", title: "Private Bank Set 6", isCompleted: false },
    ],
  },
  {
    id: "staff-nurse",
    shortName: "Staff Nurse",
    title: "Staff Nurse | 50 Sets",
    subtitle: "50 Sets",
    description:
      "Complete question bank for Staff Nurse examination covering all essential topics and previous year questions.",
    bgColor: "bg-gradient-to-br from-purple-600 to-purple-700",
    glowColor: "bg-purple-600",
    tags: ["Medical", "Nursing", "Healthcare"],
    lastUpdated: "05 May",
    language: "ENGLISH",
    purchases: 423,
    originalPrice: 300,
    price: 240,
    examDetails: {
      time: "60 mins",
      fullMarks: "60 marks",
      passMarks: "24 marks",
      validityTime: "365 days",
      negativeMarking: "-10 percent",
      numberOfQuestions: "30 question",
    },
    sets: [
      { id: "sn-1", title: "Staff Nurse Set 1", isCompleted: false },
      { id: "sn-2", title: "Staff Nurse Set 2", isCompleted: false },
      { id: "sn-3", title: "Staff Nurse Set 3", isCompleted: false },
      { id: "sn-4", title: "Staff Nurse Set 4", isCompleted: false },
      { id: "sn-5", title: "Staff Nurse Set 5", isCompleted: false },
      { id: "sn-6", title: "Staff Nurse Set 6", isCompleted: false },
    ],
  },
  {
    id: "anm",
    shortName: "अ.न.मी.",
    title: "अ० न० मी० | ANM 30 Sets",
    subtitle: "30 Sets",
    description:
      "Comprehensive question bank for ANM (Auxiliary Nurse Midwife) examination with detailed explanations.",
    bgColor: "bg-gradient-to-br from-purple-600 to-purple-700",
    glowColor: "bg-purple-600",
    tags: ["Medical", "Nursing", "Healthcare"],
    lastUpdated: "28 Apr",
    language: "NEPALI",
    purchases: 287,
    originalPrice: 220,
    price: 180,
    examDetails: {
      time: "45 mins",
      fullMarks: "50 marks",
      passMarks: "20 marks",
      validityTime: "365 days",
      negativeMarking: "-15 percent",
      numberOfQuestions: "25 question",
    },
    sets: [
      { id: "anm-1", title: "ANM Set 1", isCompleted: false },
      { id: "anm-2", title: "ANM Set 2", isCompleted: false },
      { id: "anm-3", title: "ANM Set 3", isCompleted: false },
      { id: "anm-4", title: "ANM Set 4", isCompleted: false },
      { id: "anm-5", title: "ANM Set 5", isCompleted: false },
      { id: "anm-6", title: "ANM Set 6", isCompleted: false },
    ],
  },
  {
    id: "ahw",
    shortName: "अ.हे.व.",
    title: "अ० हे० व० | Aa.He.Ba | AHW 30 Sets",
    subtitle: "30 Sets",
    description: "Complete question bank for AHW (Auxiliary Health Worker) examination with previous year questions.",
    bgColor: "bg-gradient-to-br from-indigo-600 to-indigo-700",
    glowColor: "bg-indigo-600",
    tags: ["Medical", "Healthcare"],
    lastUpdated: "20 Apr",
    language: "NEPALI",
    purchases: 198,
    originalPrice: 220,
    price: 180,
    examDetails: {
      time: "45 mins",
      fullMarks: "50 marks",
      passMarks: "20 marks",
      validityTime: "365 days",
      negativeMarking: "-15 percent",
      numberOfQuestions: "25 question",
    },
    sets: [
      { id: "ahw-1", title: "AHW Set 1", isCompleted: false },
      { id: "ahw-2", title: "AHW Set 2", isCompleted: false },
      { id: "ahw-3", title: "AHW Set 3", isCompleted: false },
      { id: "ahw-4", title: "AHW Set 4", isCompleted: false },
      { id: "ahw-5", title: "AHW Set 5", isCompleted: false },
      { id: "ahw-6", title: "AHW Set 6", isCompleted: false },
    ],
  },
  {
    id: "adbl",
    shortName: "ADBL",
    title: "ADBL 4 & 5 Level 25 Sets",
    subtitle: "25 Sets",
    description:
      "Comprehensive question bank for Agricultural Development Bank Limited (ADBL) Level 4 & 5 examinations.",
    bgColor: "bg-gradient-to-br from-green-600 to-green-700",
    glowColor: "bg-green-600",
    tags: ["Banking", "Agriculture", "Government Job"],
    lastUpdated: "15 Apr",
    language: "ENGLISH",
    purchases: 176,
    originalPrice: 200,
    price: 160,
    examDetails: {
      time: "40 mins",
      fullMarks: "50 marks",
      passMarks: "20 marks",
      validityTime: "365 days",
      negativeMarking: "-20 percent",
      numberOfQuestions: "25 question",
    },
    sets: [
      { id: "adbl-1", title: "ADBL Set 1", isCompleted: false },
      { id: "adbl-2", title: "ADBL Set 2", isCompleted: false },
      { id: "adbl-3", title: "ADBL Set 3", isCompleted: false },
      { id: "adbl-4", title: "ADBL Set 4", isCompleted: false },
      { id: "adbl-5", title: "ADBL Set 5", isCompleted: false },
      { id: "adbl-6", title: "ADBL Set 6", isCompleted: false },
    ],
  },
  {
    id: "nrb",
    shortName: "NRB",
    title: "NRB Level 4 & 6 Pre Test 25 Sets",
    subtitle: "25 Sets",
    description: "Complete question bank for Nepal Rastra Bank (NRB) Level 4 & 6 preliminary examinations.",
    bgColor: "bg-gradient-to-br from-blue-800 to-blue-900",
    glowColor: "bg-blue-800",
    tags: ["Banking", "Central Bank", "Government Job"],
    lastUpdated: "10 Apr",
    language: "ENGLISH",
    purchases: 234,
    originalPrice: 250,
    price: 200,
    examDetails: {
      time: "45 mins",
      fullMarks: "50 marks",
      passMarks: "20 marks",
      validityTime: "365 days",
      negativeMarking: "-25 percent",
      numberOfQuestions: "25 question",
    },
    sets: [
      { id: "nrb-1", title: "NRB Set 1", isCompleted: false },
      { id: "nrb-2", title: "NRB Set 2", isCompleted: false },
      { id: "nrb-3", title: "NRB Set 3", isCompleted: false },
      { id: "nrb-4", title: "NRB Set 4", isCompleted: false },
      { id: "nrb-5", title: "NRB Set 5", isCompleted: false },
      { id: "nrb-6", title: "NRB Set 6", isCompleted: false },
    ],
  },
  {
    id: "rbb",
    shortName: "RBB",
    title: "RBB | 4th Level | Pre Test | 30 Sets",
    subtitle: "30 Sets",
    description: "Comprehensive question bank for Rastriya Banijya Bank (RBB) 4th Level preliminary examinations.",
    bgColor: "bg-gradient-to-br from-blue-600 to-blue-700",
    glowColor: "bg-blue-600",
    tags: ["Banking", "Government Job"],
    lastUpdated: "05 Apr",
    language: "ENGLISH",
    purchases: 198,
    originalPrice: 220,
    price: 180,
    examDetails: {
      time: "40 mins",
      fullMarks: "50 marks",
      passMarks: "20 marks",
      validityTime: "365 days",
      negativeMarking: "-20 percent",
      numberOfQuestions: "25 question",
    },
    sets: [
      { id: "rbb-1", title: "RBB Set 1", isCompleted: false },
      { id: "rbb-2", title: "RBB Set 2", isCompleted: false },
      { id: "rbb-3", title: "RBB Set 3", isCompleted: false },
      { id: "rbb-4", title: "RBB Set 4", isCompleted: false },
      { id: "rbb-5", title: "RBB Set 5", isCompleted: false },
      { id: "rbb-6", title: "RBB Set 6", isCompleted: false },
    ],
  },
  {
    id: "ntc",
    shortName: "NTC",
    title: "NTC Level 7 Question Bank 1st Paper 30 Sets",
    subtitle: "30 Sets",
    description: "Complete question bank for Nepal Telecom Corporation (NTC) Level 7 1st Paper examination.",
    bgColor: "bg-gradient-to-br from-blue-700 to-blue-800",
    glowColor: "bg-blue-700",
    tags: ["Telecom", "Government Job", "Technical"],
    lastUpdated: "01 Apr",
    language: "ENGLISH",
    purchases: 156,
    originalPrice: 250,
    price: 200,
    examDetails: {
      time: "45 mins",
      fullMarks: "50 marks",
      passMarks: "20 marks",
      validityTime: "365 days",
      negativeMarking: "-25 percent",
      numberOfQuestions: "25 question",
    },
    sets: [
      { id: "ntc-1", title: "NTC Set 1", isCompleted: false },
      { id: "ntc-2", title: "NTC Set 2", isCompleted: false },
      { id: "ntc-3", title: "NTC Set 3", isCompleted: false },
      { id: "ntc-4", title: "NTC Set 4", isCompleted: false },
      { id: "ntc-5", title: "NTC Set 5", isCompleted: false },
      { id: "ntc-6", title: "NTC Set 6", isCompleted: false },
    ],
  },
]
